# Actions 탭에 나타날 Workflow 이름
name: Java CI with Gradle

# Workflow가 실행되지 위한 조건(트리거)
# develop 브랜치에 push, pull request가 일어 났을 경우 Actions가 실행됨
#on:
#  pull_request:
#    branches: [ "develop" ]

# Workflow의 job 목록
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 6

      - name: Debug workspace
        run: ls -R src

      - name: Create application-test.yml
        run: |
          mkdir -p src/test/resources
          echo "${{ secrets.APPLICATION_YML_TEST }}" > src/test/resources/application-test.yml

      - name: Validate application-test.yml
        run: cat src/test/resources/application-test.yml

      - name: Build without cache
        run: ./gradlew clean build -Dspring.profiles.active=test --no-build-cache
        env:
          JWT_SECRET: ${{ secrets.jwt_secret_key }}

      - name: Run Tests
        run: ./gradlew test -Dspring.profiles.active=default
        env:
          JWT_SECRET: ${{ secrets.jwt_secret_key }}

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0