# Actions 탭에 나타날 Workflow 이름
name: Java CI with Gradle

# Workflow가 실행되지 위한 조건(트리거)
# develop 브랜치에 push, pull request가 일어 났을 경우 Actions가 실행됨
on:
  pull_request:
    branches: [ "NON" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
          - name: daengle-payment-api
            path: daengle-payment-api
          - name: daengle-user
            path: daengle-user-api
          - name: daengle-vet
            path: daengle-vet-api
          - name: daengle-groomer
            path: daengle-groomer-api
          - name: daengle-chat
            path: daengle-chat-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Debug current directory
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing files in the current directory:"
          ls -l

      - name: Debug workspace
        run: |
          echo "Listing files in the module path:"
          ls -l ${{ matrix.module.path }}

      - name: Create application-test.yml
        run: |
          mkdir -p ${{ matrix.module.path }}/src/test/resources
          echo "${{ secrets.APPLICATION_YML_TEST }}" > ${{ matrix.module.path }}/src/test/resources/application-test.yml

      - name: Build and Test
        run: |
          ./gradlew :${{ matrix.module.name }}:build -Dspring.profiles.active=prod --no-build-cache
          cd ${{ matrix.module.path }}
        env:
          JWT_SECRET: ${{ secrets.jwt_secret_key }}

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
