name: Deploy to Develop EC2

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ] # 테스트 용

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      all_modules: ${{ steps.changes.outputs.all_modules }}
      daengle-chat: ${{ steps.changes.outputs.daengle-chat }}
      daengle-groomer: ${{ steps.changes.outputs.daengle-groomer }}
      daengle-payment: ${{ steps.changes.outputs.daengle-payment }}
      daengle-user: ${{ steps.changes.outputs.daengle-user }}
      daengle-vet: ${{ steps.changes.outputs.daengle-vet }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 Git 히스토리 가져오기

      - name: Check for changes
        id: changes
        run: |
          CHANGED_FILES=$(git diff --name-only origin/develop...HEAD)
          echo "Changed files: $CHANGED_FILES"

          # 공통 모듈 감지: 모든 모듈 재배포
          if echo "$CHANGED_FILES" | grep -E 'daengle-auth|daengle-domain|daengle-notification|daengle-persistence-(mysql|dynamodb)'; then
            echo "all_modules=true" >> $GITHUB_OUTPUT
          else
            echo "all_modules=false" >> $GITHUB_OUTPUT
          fi

          # 개별 모듈 감지
          for module in daengle-chat-api daengle-groomer-api daengle-payment-api daengle-user-api daengle-vet-api; do
            MODULE_NAME="${module/-api/}"
            if echo "$CHANGED_FILES" | grep -E "$module"; then
              echo "$MODULE_NAME=true" >> $GITHUB_OUTPUT
            else
              echo "$MODULE_NAME=false" >> $GITHUB_OUTPUT
            fi
          done

  deploy:
    needs: check-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - name: daengle-chat
            path: daengle-chat-api
          - name: daengle-groomer
            path: daengle-groomer-api
          - name: daengle-payment
            path: daengle-payment-api
          - name: daengle-user
            path: daengle-user-api
          - name: daengle-vet
            path: daengle-vet-api
      max-parallel: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 변경된 모듈 여부 확인
      - name: Check Deployment Condition
        id: skip-check
        run: |
          if [[ "${{ needs.check-changes.outputs.all_modules }}" == "true" || "${{ needs.check-changes.outputs[matrix.module.name] }}" == "true" ]]; then
            echo "deploy=true" >> $GITHUB_OUTPUT
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi

      # 변경사항이 없는 경우 스킵
      - name: Skip Unchanged Modules
        if: steps.skip-check.outputs.deploy == 'false'
        run: echo "No changes detected in ${{ matrix.module.name }}. Skipping deployment."

      # EC2 서버 호스트 설정
      - name: Resolve EC2 Host
        if: steps.skip-check.outputs.deploy == 'true'
        id: resolve-host
        run: |
          case "${{ matrix.module.name }}" in
            "daengle-chat")
              echo "EC2_HOST=${{ secrets.SSH_CHAT_HOST }}" >> $GITHUB_ENV
              ;;
            "daengle-groomer")
              echo "EC2_HOST=${{ secrets.SSH_GROOMER_HOST }}" >> $GITHUB_ENV
              ;;
            "daengle-payment")
              echo "EC2_HOST=${{ secrets.SSH_PAYMENT_HOST }}" >> $GITHUB_ENV
              ;;
            "daengle-user")
              echo "EC2_HOST=${{ secrets.SSH_USER_HOST }}" >> $GITHUB_ENV
              ;;
            "daengle-vet")
              echo "EC2_HOST=${{ secrets.SSH_VET_HOST }}" >> $GITHUB_ENV
              ;;
          esac
          echo "Resolved EC2_HOST: $EC2_HOST"

      # Build 및 Docker Push
      - name: Set up JDK 17
        if: steps.skip-check.outputs.deploy == 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        if: steps.skip-check.outputs.deploy == 'true'
        run: ./gradlew clean :${{ matrix.module.path }}:build -x test

      - name: Log in to Amazon ECR
        if: steps.skip-check.outputs.deploy == 'true'
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ROOT_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_ROOT_SECRET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build and Push Docker Image
        if: steps.skip-check.outputs.deploy == 'true'
        run: |
          IMAGE_TAG="${{ matrix.module.name }}-$(date +%Y%m%d%H%M%S)"
          docker build --platform linux/amd64 --build-arg JAR_FILE=build/libs/${{ matrix.module.name }}-api-0.0.1-SNAPSHOT.jar -t ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG .
          docker tag ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG ${{ secrets.ECR_REPOSITORY_URI }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

      # Deploy to EC2
      - name: Set up SSH
        if: steps.skip-check.outputs.deploy == 'true'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy to EC2
        if: steps.skip-check.outputs.deploy == 'true'
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@$EC2_HOST << 'EOF'
            export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
            export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            export AWS_REGION="${{ secrets.AWS_REGION }}"
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

            CONTAINER_NAME="${{ matrix.module.name }}-container"
            docker pull ${{ secrets.ECR_REPOSITORY_URI }}:latest
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker run -d --name $CONTAINER_NAME -p 8080:8080 ${{ secrets.ECR_REPOSITORY_URI }}:latest
          EOF

      - name: Deployment Complete
        if: steps.skip-check.outputs.deploy == 'true'
        run: echo "Deployment for ${{ matrix.module.name }} completed successfully!"