name: Deploy to Develop EC2
on:
  pull_request:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
          - name: daengle-payment
            path: daengle-payment-api
            ssh_host_var: SSH_PAYMENT_HOST
          - name: daengle-user
            path: daengle-user-api
            ssh_host_var: SSH_USER_HOST
          - name: daengle-vet
            path: daengle-vet-api
            ssh_host_var: SSH_VET_HOST
          - name: daengle-groomer
            path: daengle-groomer-api
            ssh_host_var: SSH_GROOMER_HOST

    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PAYMENT_HOST: ${{ secrets.SSH_PAYMENT_HOST }}
      SSH_USER_HOST: ${{ secrets.SSH_USER_HOST }}
      SSH_VET_HOST: ${{ secrets.SSH_VET_HOST }}
      SSH_GROOMER_HOST: ${{ secrets.SSH_GROOMER_HOST }}

    steps:
      # 1. Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Create application.yml
      - name: Create application.yml
        run: |
          mkdir -p ${{ matrix.module.path }}/src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ${{ matrix.module.path }}/src/main/resources/application.yml

      # 3. Create .env file
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > ${{ matrix.module.path }}/.env

      # 4. Set up JDK and Build JAR
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Gradle
        run: |
          ./gradlew :${{ matrix.module.name }}:build -x test

      # 5. Verify Build Output
      - name: Verify Build Output
        run: ls -l ${{ matrix.module.path }}/build/libs

      # 6. Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # 7. Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          set -e
          cd ${{ matrix.module.path }}
          
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          
          echo "Building Docker image..."
          docker build --platform linux/amd64 --build-arg JAR_FILE=build/libs/${{ matrix.module.name }}-api-0.0.1-SNAPSHOT.jar -t ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG .
          docker tag ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG ${{ secrets.ECR_REPOSITORY_URI }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

      # 8. Set up SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      # 9. Set up EC2 Host from Secrets
      - name: Set up EC2 Host
        run: |
          EC2_HOST=${{ secrets[ matrix.module.ssh_host_var ] }}
          echo "Resolved EC2_HOST: $EC2_HOST"
          echo "EC2_HOST=$EC2_HOST" >> $GITHUB_ENV

      # 10. Deploy to EC2
      - name: Deploy to EC2
        run: |
          set -e
          echo "=== Logging into EC2 ==="
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@$EC2_HOST "echo 'Connected to EC2 instance'"
          
          MODULE=${{ matrix.module.name }}
          IMAGE_TAG=${IMAGE_TAG}
          CONTAINER_NAME="${{matrix.module.name}}-container"
          
          # Pull latest image
          docker pull ${{ secrets.ECR_REPOSITORY_URI }}:latest || { echo "Docker pull failed"; exit 1; }
          
          echo "=== Stopping and removing existing container ==="
          docker ps --filter "name=$CONTAINER_NAME" | grep $CONTAINER_NAME && docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME || echo "No running container to stop."
          
          echo "=== Running new container ==="
          docker run -d --name $CONTAINER_NAME -p 8080:8080 ${{ secrets.ECR_REPOSITORY_URI }}:latest || { echo "Docker run failed"; exit 1; }
          
          echo "=== Deployment completed successfully ==="