name: Deploy to EC2

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Create .env file
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      # 3. Verify .env File
      - name: Verify .env File
        run: cat .env

      # 4. Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          set -e
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          echo "Building Docker image..."
          docker build --platform linux/amd64 --build-arg JAR_FILE=build/libs/daengle-server-0.0.1-SNAPSHOT.jar -t ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG .
          docker tag ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG ${{ secrets.ECR_REPOSITORY_URI }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

      # 5. Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          echo "=== Logging into ECR ==="
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

          echo "=== Pulling the latest Docker image ==="
          docker pull ${{ secrets.ECR_REPOSITORY_URI }}:latest || { echo "Docker pull failed"; exit 1; }

          echo "=== Stopping and removing existing container ==="
          CONTAINER_ID=$(docker ps -aq --filter "name=spring-app")
          if [ -n "$CONTAINER_ID" ]; then
            echo "Stopping existing container..."
            docker stop spring-app || { echo "Failed to stop container"; exit 1; }
            docker rm spring-app || { echo "Failed to remove container"; exit 1; }
          else
            echo "No existing container to stop."
          fi

          echo "=== Running new container ==="
          docker run -d --name spring-app -p 8080:8080 ${{ secrets.ECR_REPOSITORY_URI }}:latest || { echo "Docker run failed"; exit 1; }

          echo "=== Verifying the new container ==="
          sleep 10
          if ! docker ps --filter "name=spring-app" --filter "status=running" | grep spring-app; then
            echo "New container is not running. Check logs for errors."
            docker logs spring-app
            exit 1
          fi

          echo "=== Deployment completed successfully ==="
          EOF