name: Java CI with Gradle (Prod Integration)

on:
  pull_request:
    branches: [ "main" ]  # main 브랜치에 대한 pull request 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
          - name: daengle-payment
            path: daengle-payment-api
          - name: daengle-user
            path: daengle-user-api
          - name: daengle-vet
            path: daengle-vet-api
          - name: daengle-groomer
            path: daengle-groomer-api

    permissions:
      contents: read  # contents에 대한 권한을 read로 설정

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Debug workspace
        run: ls -R src

      - name: Create application-prod.yml
        run: |
          mkdir -p ${{ matrix.module.path }}/src/test/resources
          echo "${{ secrets.APPLICATION_YML_PROD }}" > ${{ matrix.module.path }}/src/test/resources/application-prod.yml

      - name: Build and Test with Gradle
        run: |
          cd ${{ matrix.module.path }}
          ./gradlew clean build -Dspring.profiles.active=prod --no-build-cache
        env:
          JWT_SECRET: ${{ secrets.MAIN_JWT_SECRET_KEY }}

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0