name: Java CI with Gradle (Main)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build -Dspring.profiles.active=main
        env:
          JWT_SECRET: ${{ secrets.MAIN_JWT_SECRET_KEY }}

      - name: Run Tests
        run: ./gradlew test -Dspring.profiles.active=main